### ISSUE TITLE
Encoding with Ace Serializer.

### ISSUE THREAD

**Issue by acornellier** [Zireael-N/node-weakauras-parser#10]
Hey, thanks for the great tool! I'm trying to use it to decode/encode MDT strings. Decoding works great since you support both serializers, but encoding does not since the tool always uses the new serializer, but MDT expects the old one (Ace).

Ideally there would be an option in the `encode` function to use the Ace Serializer. But I understand if you don't want to support both. Otherwise, I'm gonna try to build a version myself from my fork.. wish me luck :)

**Comment by Zireael-N** [comment]
Hi!

I currently do not have access to a device with required development tools, so it may take a while.

In the meantime, to use MDT-compatible serialization you need to:
1) Import [ace_serialization::Serializer (instead of lib_serialize::Serializer) in native/src/common.rs](https://github.com/Zireael-N/node-weakauras-parser/blob/00180bc31fe73f4d3d7ba4d825e17d78541bfbce/native/src/common.rs#L8), you'll also need to [replace `serialized.as_slice()` with `serialized.as_bytes()` at line #101](https://github.com/Zireael-N/node-weakauras-parser/blob/e8c65de4aac57b5799afcc57bdb85b8c3505eaa1/native/src/common.rs#L101);
2) Replace [`!WA:2!` with `!` in native/src/base64/encode/mod.rs](https://github.com/Zireael-N/node-weakauras-parser/blob/e8c65de4aac57b5799afcc57bdb85b8c3505eaa1/native/src/base64/encode/mod.rs#L48).

**Comment by acornellier** [comment]
I did it! Was able to make the change, test, build, and publish the whole thing! And I learned some Rust along the way, thanks :)

**Comment by Zireael-N** [comment]
I've added an optional argument to `encode` and `encodeSync` and published a new version.

If you use TypeScript, you can do the following:
```ts
import { FormatVersion, encode } from 'node-weakauras-parser';

await encode({}, FormatVersion.Deflate);
```

If you use plain JS, just pass `1` instead.

**Comment by acornellier** [comment]
Thanks a lot! It worked perfectly. I can delete my hacky fork now :D
